"""Creacion inicial del esquema basado en modelos

Revision ID: fa155d6b27e2
Revises: 
Create Date: 2025-04-17 00:34:38.823864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fa155d6b27e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_trabajo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tipo_identificacion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('identificacion_fiscal', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('persona_contacto', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_email'), 'cliente', ['email'], unique=True)
    op.create_index(op.f('ix_cliente_identificacion_fiscal'), 'cliente', ['identificacion_fiscal'], unique=True)
    op.create_index(op.f('ix_cliente_nombre'), 'cliente', ['nombre'], unique=False)
    op.create_table('herramienta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('codigo_interno', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herramienta_codigo_interno'), 'herramienta', ['codigo_interno'], unique=True)
    op.create_table('material_consumible',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unidad_medida', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rendimiento_m2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ubicacion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_consumible_sku'), 'material_consumible', ['sku'], unique=True)
    op.create_table('material_dimensional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('espesor_nominal', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad_dimension', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_dimensional_sku'), 'material_dimensional', ['sku'], unique=True)
    op.create_table('material_simple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unidad_medida', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ubicacion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_simple_sku'), 'material_simple', ['sku'], unique=True)
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_accion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('nombre_recurso', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_accion', 'nombre_recurso', name='uq_permiso_accion_recurso')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=True)
    op.create_table('servicio_definicion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('unidad_cobro', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('costo_por_unidad', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('costo_por_minuto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tiempo_setup_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tiempo_preparado_min_por_unidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('factor_ih', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('factor_st', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('factor_m', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('requiere_dibujo_cnc', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicio_definicion_codigo'), 'servicio_definicion', ['codigo'], unique=True)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('contrasena_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nombre_completo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    op.create_table('formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servicio_definicion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['servicio_definicion_id'], ['servicio_definicion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formula_servicio_definicion_id'), 'formula', ['servicio_definicion_id'], unique=False)
    op.create_table('maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('numero_serie', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('area_trabajo_id', sa.Integer(), nullable=True),
    sa.Column('margen_perdida_mm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha_adquisicion', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['area_trabajo_id'], ['area_trabajo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maquina_area_trabajo_id'), 'maquina', ['area_trabajo_id'], unique=False)
    op.create_index(op.f('ix_maquina_numero_serie'), 'maquina', ['numero_serie'], unique=True)
    op.create_table('pedido_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id_vendedor', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id_vendedor'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_cliente_cliente_id'), 'pedido_cliente', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedido_cliente_estado'), 'pedido_cliente', ['estado'], unique=False)
    op.create_index(op.f('ix_pedido_cliente_usuario_id_vendedor'), 'pedido_cliente', ['usuario_id_vendedor'], unique=False)
    op.create_table('periodo_indisponibilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodo_indisponibilidad_usuario_id'), 'periodo_indisponibilidad', ['usuario_id'], unique=False)
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('usuario_area_trabajo',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('area_trabajo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_trabajo_id'], ['area_trabajo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'area_trabajo_id')
    )
    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('formula_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('tipo_material', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('material_consumible_id', sa.Integer(), nullable=True),
    sa.Column('material_simple_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_necesaria', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad_rendimiento', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion_uso', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['formula.id'], ),
    sa.ForeignKeyConstraint(['material_consumible_id'], ['material_consumible.id'], ),
    sa.ForeignKeyConstraint(['material_simple_id'], ['material_simple.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formula_item_formula_id'), 'formula_item', ['formula_id'], unique=False)
    op.create_index(op.f('ix_formula_item_material_consumible_id'), 'formula_item', ['material_consumible_id'], unique=False)
    op.create_index(op.f('ix_formula_item_material_simple_id'), 'formula_item', ['material_simple_id'], unique=False)
    op.create_table('maquina_herramienta',
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('herramienta_id', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('posicion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.ForeignKeyConstraint(['herramienta_id'], ['herramienta.id'], ),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.PrimaryKeyConstraint('maquina_id', 'herramienta_id')
    )
    op.create_table('orden_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id_supervisor', sa.Integer(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio_espera', sa.DateTime(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_estimada_finalizacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_real_finalizacion', sa.DateTime(), nullable=True),
    sa.Column('notas_supervisor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ruta_imagen_final', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_cliente_id'], ['pedido_cliente.id'], ),
    sa.ForeignKeyConstraint(['usuario_id_supervisor'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orden_produccion_estado'), 'orden_produccion', ['estado'], unique=False)
    op.create_index(op.f('ix_orden_produccion_pedido_cliente_id'), 'orden_produccion', ['pedido_cliente_id'], unique=True)
    op.create_index(op.f('ix_orden_produccion_usuario_id_supervisor'), 'orden_produccion', ['usuario_id_supervisor'], unique=False)
    op.create_table('proforma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('proforma_vinculada_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id_creador', sa.Integer(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_reserva_expira', sa.DateTime(), nullable=True),
    sa.Column('estado_reserva', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('impuestos', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_cliente_id'], ['pedido_cliente.id'], ),
    sa.ForeignKeyConstraint(['proforma_vinculada_id'], ['proforma.id'], ),
    sa.ForeignKeyConstraint(['usuario_id_creador'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proforma_estado'), 'proforma', ['estado'], unique=False)
    op.create_index(op.f('ix_proforma_pedido_cliente_id'), 'proforma', ['pedido_cliente_id'], unique=False)
    op.create_index(op.f('ix_proforma_proforma_vinculada_id'), 'proforma', ['proforma_vinculada_id'], unique=False)
    op.create_index(op.f('ix_proforma_usuario_id_creador'), 'proforma', ['usuario_id_creador'], unique=False)
    op.create_table('registro_mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id_tecnico', sa.Integer(), nullable=True),
    sa.Column('fecha_mantenimiento', sa.DateTime(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('costo_repuestos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('horas_mano_obra', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['usuario_id_tecnico'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_mantenimiento_maquina_id'), 'registro_mantenimiento', ['maquina_id'], unique=False)
    op.create_index(op.f('ix_registro_mantenimiento_usuario_id_tecnico'), 'registro_mantenimiento', ['usuario_id_tecnico'], unique=False)
    op.create_table('reporte_error_maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id_reportador', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('descripcion_error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_error', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('prioridad', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('esta_resuelto', sa.Boolean(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('usuario_id_resolutor', sa.Integer(), nullable=True),
    sa.Column('detalles_resolucion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['usuario_id_reportador'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['usuario_id_resolutor'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_error_maquina_esta_resuelto'), 'reporte_error_maquina', ['esta_resuelto'], unique=False)
    op.create_index(op.f('ix_reporte_error_maquina_maquina_id'), 'reporte_error_maquina', ['maquina_id'], unique=False)
    op.create_index(op.f('ix_reporte_error_maquina_usuario_id_reportador'), 'reporte_error_maquina', ['usuario_id_reportador'], unique=False)
    op.create_index(op.f('ix_reporte_error_maquina_usuario_id_resolutor'), 'reporte_error_maquina', ['usuario_id_resolutor'], unique=False)
    op.create_table('stock_item_dimensional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_dimensional_id', sa.Integer(), nullable=False),
    sa.Column('longitud_actual', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('ancho_actual', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('ubicacion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('es_merma', sa.Boolean(), nullable=False),
    sa.Column('stock_item_padre_id', sa.Integer(), nullable=True),
    sa.Column('orden_produccion_generadora_id', sa.Integer(), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_dimensional_id'], ['material_dimensional.id'], ),
    sa.ForeignKeyConstraint(['orden_produccion_generadora_id'], ['orden_produccion.id'], ),
    sa.ForeignKeyConstraint(['stock_item_padre_id'], ['stock_item_dimensional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_item_dimensional_estado'), 'stock_item_dimensional', ['estado'], unique=False)
    op.create_index(op.f('ix_stock_item_dimensional_material_dimensional_id'), 'stock_item_dimensional', ['material_dimensional_id'], unique=False)
    op.create_index(op.f('ix_stock_item_dimensional_orden_produccion_generadora_id'), 'stock_item_dimensional', ['orden_produccion_generadora_id'], unique=False)
    op.create_index(op.f('ix_stock_item_dimensional_stock_item_padre_id'), 'stock_item_dimensional', ['stock_item_padre_id'], unique=False)
    op.create_table('venta_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_cliente_id', sa.Integer(), nullable=False),
    sa.Column('proforma_productos_id', sa.Integer(), nullable=True),
    sa.Column('proforma_servicios_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('monto_total_final', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fecha_factura', sa.DateTime(), nullable=False),
    sa.Column('ref_factura_externa', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('estado_factura_externa', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('estado_pago', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['pedido_cliente_id'], ['pedido_cliente.id'], ),
    sa.ForeignKeyConstraint(['proforma_productos_id'], ['proforma.id'], ),
    sa.ForeignKeyConstraint(['proforma_servicios_id'], ['proforma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_factura_cliente_id'), 'venta_factura', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_venta_factura_pedido_cliente_id'), 'venta_factura', ['pedido_cliente_id'], unique=False)
    op.create_index(op.f('ix_venta_factura_proforma_productos_id'), 'venta_factura', ['proforma_productos_id'], unique=False)
    op.create_index(op.f('ix_venta_factura_proforma_servicios_id'), 'venta_factura', ['proforma_servicios_id'], unique=False)
    op.create_index(op.f('ix_venta_factura_ref_factura_externa'), 'venta_factura', ['ref_factura_externa'], unique=True)
    op.create_table('linea_proforma_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proforma_id', sa.Integer(), nullable=False),
    sa.Column('tipo_material_origen', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('stock_item_dimensional_id', sa.Integer(), nullable=True),
    sa.Column('material_consumible_id', sa.Integer(), nullable=True),
    sa.Column('material_simple_id', sa.Integer(), nullable=True),
    sa.Column('descripcion_item', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidad', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_linea', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('detalles_corte_solicitado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['material_consumible_id'], ['material_consumible.id'], ),
    sa.ForeignKeyConstraint(['material_simple_id'], ['material_simple.id'], ),
    sa.ForeignKeyConstraint(['proforma_id'], ['proforma.id'], ),
    sa.ForeignKeyConstraint(['stock_item_dimensional_id'], ['stock_item_dimensional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linea_proforma_material_material_consumible_id'), 'linea_proforma_material', ['material_consumible_id'], unique=False)
    op.create_index(op.f('ix_linea_proforma_material_material_simple_id'), 'linea_proforma_material', ['material_simple_id'], unique=False)
    op.create_index(op.f('ix_linea_proforma_material_proforma_id'), 'linea_proforma_material', ['proforma_id'], unique=False)
    op.create_index(op.f('ix_linea_proforma_material_stock_item_dimensional_id'), 'linea_proforma_material', ['stock_item_dimensional_id'], unique=False)
    op.create_table('linea_proforma_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proforma_id', sa.Integer(), nullable=False),
    sa.Column('servicio_definicion_id', sa.Integer(), nullable=False),
    sa.Column('linea_proforma_material_id', sa.Integer(), nullable=True),
    sa.Column('descripcion_servicio', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_linea', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ruta_imagen_cnc', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('detalles_adicionales', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['linea_proforma_material_id'], ['linea_proforma_material.id'], ),
    sa.ForeignKeyConstraint(['proforma_id'], ['proforma.id'], ),
    sa.ForeignKeyConstraint(['servicio_definicion_id'], ['servicio_definicion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linea_proforma_servicio_linea_proforma_material_id'), 'linea_proforma_servicio', ['linea_proforma_material_id'], unique=False)
    op.create_index(op.f('ix_linea_proforma_servicio_proforma_id'), 'linea_proforma_servicio', ['proforma_id'], unique=False)
    op.create_index(op.f('ix_linea_proforma_servicio_servicio_definicion_id'), 'linea_proforma_servicio', ['servicio_definicion_id'], unique=False)
    op.create_table('asignacion_tarea_orden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('linea_proforma_servicio_id', sa.Integer(), nullable=True),
    sa.Column('linea_proforma_material_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id_asignado', sa.Integer(), nullable=False),
    sa.Column('rol_id_contexto', sa.Integer(), nullable=False),
    sa.Column('tipo_tarea', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('estado_tarea', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio_tarea', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin_tarea', sa.DateTime(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['linea_proforma_material_id'], ['linea_proforma_material.id'], ),
    sa.ForeignKeyConstraint(['linea_proforma_servicio_id'], ['linea_proforma_servicio.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_produccion.id'], ),
    sa.ForeignKeyConstraint(['rol_id_contexto'], ['rol.id'], ),
    sa.ForeignKeyConstraint(['usuario_id_asignado'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignacion_tarea_orden_linea_proforma_material_id'), 'asignacion_tarea_orden', ['linea_proforma_material_id'], unique=False)
    op.create_index(op.f('ix_asignacion_tarea_orden_linea_proforma_servicio_id'), 'asignacion_tarea_orden', ['linea_proforma_servicio_id'], unique=False)
    op.create_index(op.f('ix_asignacion_tarea_orden_orden_id'), 'asignacion_tarea_orden', ['orden_id'], unique=False)
    op.create_index(op.f('ix_asignacion_tarea_orden_rol_id_contexto'), 'asignacion_tarea_orden', ['rol_id_contexto'], unique=False)
    op.create_index(op.f('ix_asignacion_tarea_orden_usuario_id_asignado'), 'asignacion_tarea_orden', ['usuario_id_asignado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asignacion_tarea_orden_usuario_id_asignado'), table_name='asignacion_tarea_orden')
    op.drop_index(op.f('ix_asignacion_tarea_orden_rol_id_contexto'), table_name='asignacion_tarea_orden')
    op.drop_index(op.f('ix_asignacion_tarea_orden_orden_id'), table_name='asignacion_tarea_orden')
    op.drop_index(op.f('ix_asignacion_tarea_orden_linea_proforma_servicio_id'), table_name='asignacion_tarea_orden')
    op.drop_index(op.f('ix_asignacion_tarea_orden_linea_proforma_material_id'), table_name='asignacion_tarea_orden')
    op.drop_table('asignacion_tarea_orden')
    op.drop_index(op.f('ix_linea_proforma_servicio_servicio_definicion_id'), table_name='linea_proforma_servicio')
    op.drop_index(op.f('ix_linea_proforma_servicio_proforma_id'), table_name='linea_proforma_servicio')
    op.drop_index(op.f('ix_linea_proforma_servicio_linea_proforma_material_id'), table_name='linea_proforma_servicio')
    op.drop_table('linea_proforma_servicio')
    op.drop_index(op.f('ix_linea_proforma_material_stock_item_dimensional_id'), table_name='linea_proforma_material')
    op.drop_index(op.f('ix_linea_proforma_material_proforma_id'), table_name='linea_proforma_material')
    op.drop_index(op.f('ix_linea_proforma_material_material_simple_id'), table_name='linea_proforma_material')
    op.drop_index(op.f('ix_linea_proforma_material_material_consumible_id'), table_name='linea_proforma_material')
    op.drop_table('linea_proforma_material')
    op.drop_index(op.f('ix_venta_factura_ref_factura_externa'), table_name='venta_factura')
    op.drop_index(op.f('ix_venta_factura_proforma_servicios_id'), table_name='venta_factura')
    op.drop_index(op.f('ix_venta_factura_proforma_productos_id'), table_name='venta_factura')
    op.drop_index(op.f('ix_venta_factura_pedido_cliente_id'), table_name='venta_factura')
    op.drop_index(op.f('ix_venta_factura_cliente_id'), table_name='venta_factura')
    op.drop_table('venta_factura')
    op.drop_index(op.f('ix_stock_item_dimensional_stock_item_padre_id'), table_name='stock_item_dimensional')
    op.drop_index(op.f('ix_stock_item_dimensional_orden_produccion_generadora_id'), table_name='stock_item_dimensional')
    op.drop_index(op.f('ix_stock_item_dimensional_material_dimensional_id'), table_name='stock_item_dimensional')
    op.drop_index(op.f('ix_stock_item_dimensional_estado'), table_name='stock_item_dimensional')
    op.drop_table('stock_item_dimensional')
    op.drop_index(op.f('ix_reporte_error_maquina_usuario_id_resolutor'), table_name='reporte_error_maquina')
    op.drop_index(op.f('ix_reporte_error_maquina_usuario_id_reportador'), table_name='reporte_error_maquina')
    op.drop_index(op.f('ix_reporte_error_maquina_maquina_id'), table_name='reporte_error_maquina')
    op.drop_index(op.f('ix_reporte_error_maquina_esta_resuelto'), table_name='reporte_error_maquina')
    op.drop_table('reporte_error_maquina')
    op.drop_index(op.f('ix_registro_mantenimiento_usuario_id_tecnico'), table_name='registro_mantenimiento')
    op.drop_index(op.f('ix_registro_mantenimiento_maquina_id'), table_name='registro_mantenimiento')
    op.drop_table('registro_mantenimiento')
    op.drop_index(op.f('ix_proforma_usuario_id_creador'), table_name='proforma')
    op.drop_index(op.f('ix_proforma_proforma_vinculada_id'), table_name='proforma')
    op.drop_index(op.f('ix_proforma_pedido_cliente_id'), table_name='proforma')
    op.drop_index(op.f('ix_proforma_estado'), table_name='proforma')
    op.drop_table('proforma')
    op.drop_index(op.f('ix_orden_produccion_usuario_id_supervisor'), table_name='orden_produccion')
    op.drop_index(op.f('ix_orden_produccion_pedido_cliente_id'), table_name='orden_produccion')
    op.drop_index(op.f('ix_orden_produccion_estado'), table_name='orden_produccion')
    op.drop_table('orden_produccion')
    op.drop_table('maquina_herramienta')
    op.drop_index(op.f('ix_formula_item_material_simple_id'), table_name='formula_item')
    op.drop_index(op.f('ix_formula_item_material_consumible_id'), table_name='formula_item')
    op.drop_index(op.f('ix_formula_item_formula_id'), table_name='formula_item')
    op.drop_table('formula_item')
    op.drop_table('usuario_rol')
    op.drop_table('usuario_area_trabajo')
    op.drop_table('rol_permiso')
    op.drop_index(op.f('ix_periodo_indisponibilidad_usuario_id'), table_name='periodo_indisponibilidad')
    op.drop_table('periodo_indisponibilidad')
    op.drop_index(op.f('ix_pedido_cliente_usuario_id_vendedor'), table_name='pedido_cliente')
    op.drop_index(op.f('ix_pedido_cliente_estado'), table_name='pedido_cliente')
    op.drop_index(op.f('ix_pedido_cliente_cliente_id'), table_name='pedido_cliente')
    op.drop_table('pedido_cliente')
    op.drop_index(op.f('ix_maquina_numero_serie'), table_name='maquina')
    op.drop_index(op.f('ix_maquina_area_trabajo_id'), table_name='maquina')
    op.drop_table('maquina')
    op.drop_index(op.f('ix_formula_servicio_definicion_id'), table_name='formula')
    op.drop_table('formula')
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_servicio_definicion_codigo'), table_name='servicio_definicion')
    op.drop_table('servicio_definicion')
    op.drop_index(op.f('ix_rol_nombre'), table_name='rol')
    op.drop_table('rol')
    op.drop_table('permiso')
    op.drop_index(op.f('ix_material_simple_sku'), table_name='material_simple')
    op.drop_table('material_simple')
    op.drop_index(op.f('ix_material_dimensional_sku'), table_name='material_dimensional')
    op.drop_table('material_dimensional')
    op.drop_index(op.f('ix_material_consumible_sku'), table_name='material_consumible')
    op.drop_table('material_consumible')
    op.drop_index(op.f('ix_herramienta_codigo_interno'), table_name='herramienta')
    op.drop_table('herramienta')
    op.drop_index(op.f('ix_cliente_nombre'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_identificacion_fiscal'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_email'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_table('area_trabajo')
    # ### end Alembic commands ###
