"""Crear estructura inicial de tablas

Revision ID: fbc9e68e506f
Revises: 
Create Date: 2025-04-05 20:33:01.407545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fbc9e68e506f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('persona_contacto', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('identificacion_fiscal', sa.String(length=50), nullable=True, comment='RUC/CI u otro identificador'),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='email_UNIQUE'),
    sa.UniqueConstraint('identificacion_fiscal', name='identificacion_fiscal_UNIQUE')
    )
    op.create_index('idx_cliente_nombre', 'cliente', ['nombre'], unique=False)
    op.create_index(op.f('ix_cliente_identificacion_fiscal'), 'cliente', ['identificacion_fiscal'], unique=False)
    op.create_index(op.f('ix_cliente_nombre'), 'cliente', ['nombre'], unique=False)
    op.create_table('definicion_producto_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('PRODUCTO', 'SERVICIO', name='tipo_producto_servicio_enum'), nullable=False),
    sa.Column('precio_estandar', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True, comment='ej: unidad, hora, corte, m², etc.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('CNC', 'CORTE', 'OTRO', name='tipo_maquina_enum'), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('numero_serie', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.Enum('OPERATIVA', 'EN_MANTENIMIENTO', 'AVERIADA', name='estado_maquina_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie', name='numero_serie_UNIQUE')
    )
    op.create_index(op.f('ix_maquina_numero_serie'), 'maquina', ['numero_serie'], unique=False)
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Ej: proforma:crear, inventario:leer'),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='nombre_UNIQUE')
    )
    op.create_index(op.f('ix_permiso_nombre'), 'permiso', ['nombre'], unique=False)
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Ej: Administrador, Vendedor, Supervisor'),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='nombre_UNIQUE')
    )
    op.create_index(op.f('ix_rol_nombre'), 'rol', ['nombre'], unique=False)
    op.create_table('tipo_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True, comment='ej: m², kg, L, unidad'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Nombre de usuario para login'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='email_UNIQUE'),
    sa.UniqueConstraint('username', name='username_UNIQUE')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=False)
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=False)
    op.create_table('item_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_material_id', sa.Integer(), nullable=False),
    sa.Column('longitud', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='Dimensión 1 (ej. metros, cm)'),
    sa.Column('ancho', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='Dimensión 2 (ej. metros, cm)'),
    sa.Column('espesor', sa.DECIMAL(precision=10, scale=3), nullable=True, comment='Dimensión 3 (ej. metros, cm)'),
    sa.Column('cantidad', sa.DECIMAL(precision=10, scale=3), nullable=False, comment='Cantidad en unidad_medida o 1'),
    sa.Column('ubicacion', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('es_merma', sa.Boolean(), nullable=False),
    sa.Column('item_inventario_padre_id', sa.Integer(), nullable=True, comment='FK a item_inventario si es merma'),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_inventario_padre_id'], ['item_inventario.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_material_id'], ['tipo_material.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_item_inventario_padre_idx', 'item_inventario', ['item_inventario_padre_id'], unique=False)
    op.create_index('fk_item_inventario_tipo_material_idx', 'item_inventario', ['tipo_material_id'], unique=False)
    op.create_table('periodo_indisponibilidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_periodo_indisponibilidad_usuario_idx', 'periodo_indisponibilidad', ['usuario_id'], unique=False)
    op.create_index('idx_indisp_fechas', 'periodo_indisponibilidad', ['fecha_inicio', 'fecha_fin'], unique=False)
    op.create_table('proforma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id_creador', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'PENDIENTE_COTIZACION', 'PENDIENTE_PAGO', 'APROBADA', 'RECHAZADA', 'CANCELADA', name='estado_proforma_enum'), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_ultima_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('impuestos', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id_creador'], ['usuario.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_proforma_cliente_idx', 'proforma', ['cliente_id'], unique=False)
    op.create_index('fk_proforma_usuario_idx', 'proforma', ['usuario_id_creador'], unique=False)
    op.create_index('idx_proforma_estado', 'proforma', ['estado'], unique=False)
    op.create_table('registro_mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id_tecnico', sa.Integer(), nullable=True),
    sa.Column('fecha_mantenimiento', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.Enum('PREVENTIVO', 'CORRECTIVO', name='tipo_mantenimiento_enum'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id_tecnico'], ['usuario.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_registro_mantenimiento_maquina_idx', 'registro_mantenimiento', ['maquina_id'], unique=False)
    op.create_index('fk_registro_mantenimiento_usuario_idx', 'registro_mantenimiento', ['usuario_id_tecnico'], unique=False)
    op.create_index('idx_maint_fecha', 'registro_mantenimiento', ['fecha_mantenimiento'], unique=False)
    op.create_table('reporte_error_maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id_reportador', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('descripcion_error', sa.Text(), nullable=False),
    sa.Column('esta_resuelto', sa.Boolean(), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('detalles_resolucion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquina.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id_reportador'], ['usuario.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_reporte_error_maquina_maquina_idx', 'reporte_error_maquina', ['maquina_id'], unique=False)
    op.create_index('fk_reporte_error_maquina_usuario_idx', 'reporte_error_maquina', ['usuario_id_reportador'], unique=False)
    op.create_index('idx_error_resuelto', 'reporte_error_maquina', ['esta_resuelto'], unique=False)
    op.create_table('rol_permiso',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('usuario_rol',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('linea_proforma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proforma_id', sa.Integer(), nullable=False),
    sa.Column('tipo_item', sa.Enum('ITEM_INVENTARIO', 'PRODUCTO_SERVICIO', name='tipo_item_proforma_enum'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False, comment='ID polimórfico'),
    sa.Column('cantidad', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_linea', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('detalles_descripcion', sa.Text(), nullable=True, comment='Ej: dimensiones corte'),
    sa.ForeignKeyConstraint(['proforma_id'], ['proforma.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('fk_linea_proforma_proforma_idx', 'linea_proforma', ['proforma_id'], unique=False)
    op.create_index('idx_linea_proforma_item', 'linea_proforma', ['item_id', 'tipo_item'], unique=False)
    op.create_table('orden_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proforma_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ASIGNADA', 'EN_PROGRESO_CORTE', 'EN_PROGRESO_CNC', 'EN_REVISION', 'COMPLETADA', 'ENTREGADA', 'CANCELADA', name='estado_orden_produccion_enum'), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_estimada_finalizacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_real_finalizacion', sa.DateTime(), nullable=True),
    sa.Column('notas_supervisor', sa.Text(), nullable=True),
    sa.Column('ruta_imagen_final', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.ForeignKeyConstraint(['proforma_id'], ['proforma.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proforma_id'),
    sa.UniqueConstraint('proforma_id', name='proforma_id_UNIQUE')
    )
    op.create_index('fk_orden_produccion_proforma_idx', 'orden_produccion', ['proforma_id'], unique=False)
    op.create_index('idx_orden_prod_estado', 'orden_produccion', ['estado'], unique=False)
    op.create_table('venta_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proforma_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('monto_total_final', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('fecha_factura', sa.DateTime(), nullable=False),
    sa.Column('ref_factura_externa', sa.String(length=255), nullable=True, comment='Referencia del sistema externo de facturación'),
    sa.Column('estado_pago', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proforma_id'], ['proforma.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proforma_id'),
    sa.UniqueConstraint('proforma_id', name='proforma_id_UNIQUE'),
    sa.UniqueConstraint('ref_factura_externa', name='ref_factura_externa_UNIQUE')
    )
    op.create_index('fk_venta_factura_cliente_idx', 'venta_factura', ['cliente_id'], unique=False)
    op.create_index('fk_venta_factura_proforma_idx', 'venta_factura', ['proforma_id'], unique=False)
    op.create_index('idx_venta_fecha', 'venta_factura', ['fecha_factura'], unique=False)
    op.create_index(op.f('ix_venta_factura_ref_factura_externa'), 'venta_factura', ['ref_factura_externa'], unique=False)
    op.create_table('asignacion_orden_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_asignado_contexto', sa.String(length=100), nullable=True, comment='Ej: dibujante_cotizacion, operario_corte'),
    sa.Column('fecha_asignacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_produccion.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orden_id', 'usuario_id', 'rol_asignado_contexto', name='uq_orden_usuario_rol')
    )
    op.create_index('fk_asignacion_orden_produccion_orden_idx', 'asignacion_orden_produccion', ['orden_id'], unique=False)
    op.create_index('fk_asignacion_orden_produccion_usuario_idx', 'asignacion_orden_produccion', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk_asignacion_orden_produccion_usuario_idx', table_name='asignacion_orden_produccion')
    op.drop_index('fk_asignacion_orden_produccion_orden_idx', table_name='asignacion_orden_produccion')
    op.drop_table('asignacion_orden_produccion')
    op.drop_index(op.f('ix_venta_factura_ref_factura_externa'), table_name='venta_factura')
    op.drop_index('idx_venta_fecha', table_name='venta_factura')
    op.drop_index('fk_venta_factura_proforma_idx', table_name='venta_factura')
    op.drop_index('fk_venta_factura_cliente_idx', table_name='venta_factura')
    op.drop_table('venta_factura')
    op.drop_index('idx_orden_prod_estado', table_name='orden_produccion')
    op.drop_index('fk_orden_produccion_proforma_idx', table_name='orden_produccion')
    op.drop_table('orden_produccion')
    op.drop_index('idx_linea_proforma_item', table_name='linea_proforma')
    op.drop_index('fk_linea_proforma_proforma_idx', table_name='linea_proforma')
    op.drop_table('linea_proforma')
    op.drop_table('usuario_rol')
    op.drop_table('rol_permiso')
    op.drop_index('idx_error_resuelto', table_name='reporte_error_maquina')
    op.drop_index('fk_reporte_error_maquina_usuario_idx', table_name='reporte_error_maquina')
    op.drop_index('fk_reporte_error_maquina_maquina_idx', table_name='reporte_error_maquina')
    op.drop_table('reporte_error_maquina')
    op.drop_index('idx_maint_fecha', table_name='registro_mantenimiento')
    op.drop_index('fk_registro_mantenimiento_usuario_idx', table_name='registro_mantenimiento')
    op.drop_index('fk_registro_mantenimiento_maquina_idx', table_name='registro_mantenimiento')
    op.drop_table('registro_mantenimiento')
    op.drop_index('idx_proforma_estado', table_name='proforma')
    op.drop_index('fk_proforma_usuario_idx', table_name='proforma')
    op.drop_index('fk_proforma_cliente_idx', table_name='proforma')
    op.drop_table('proforma')
    op.drop_index('idx_indisp_fechas', table_name='periodo_indisponibilidad')
    op.drop_index('fk_periodo_indisponibilidad_usuario_idx', table_name='periodo_indisponibilidad')
    op.drop_table('periodo_indisponibilidad')
    op.drop_index('fk_item_inventario_tipo_material_idx', table_name='item_inventario')
    op.drop_index('fk_item_inventario_padre_idx', table_name='item_inventario')
    op.drop_table('item_inventario')
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('tipo_material')
    op.drop_index(op.f('ix_rol_nombre'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_permiso_nombre'), table_name='permiso')
    op.drop_table('permiso')
    op.drop_index(op.f('ix_maquina_numero_serie'), table_name='maquina')
    op.drop_table('maquina')
    op.drop_table('definicion_producto_servicio')
    op.drop_index(op.f('ix_cliente_nombre'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_identificacion_fiscal'), table_name='cliente')
    op.drop_index('idx_cliente_nombre', table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
